docs/data-sources/query.md, go.mod, go.sum, honeycombio/data_source_query.go, honeycombio/data_source_query_test.go
=> Extend honeycombio_query

go.mod, go.sum, honeycombio/data_source_query.go, honeycombio/data_source_query_test.go, honeycombio/data_source_trigger_recipient.go, honeycombio/helpers_test.go, honeycombio/internal/hashcode/hashcode.go, honeycombio/query_spec.go, honeycombio/resource_board.go, honeycombio/resource_board_test.go, honeycombio/resource_marker.go, honeycombio/resource_trigger.go, honeycombio/resource_trigger_test.go, honeycombio/type_helpers.go
=> Refactoring for v0.1.0

honeycombio/resource_dataset_test.go
=> Avoid hardcoded dataset name in test

client/trigger.go
Pulled in from [go-honeycombio#22](https://github.com/kvrhdn/go-honeycombio/pull/22)
CC: @slizco
=> client - always show Triggered disabled status

client/query_spec.go
Adds missing RATE_AVG, RATE_MAX, and RATE_SUM
Resolves #87
=> client - update queryspec calculations

honeycombio/data_source_query_specification.go, honeycombio/data_source_query_specification_test.go
=> bugfix: 'ascending' sort order always showing diff

CHANGELOG.md
=> stage 0.3.2

.github/workflows/ci.yaml
See: https://github.com/honeycombio/terraform-provider-honeycombio/runs/5816668525?check_suite_focus=true
=> CI: fix formatting job goimports install

honeycombio/resource_query_annotation.go, honeycombio/resource_trigger.go
=> Add length validation for Query Annotation and Trigger names and descriptions

honeycombio/data_source_query_specification.go, honeycombio/data_source_query_specification_test.go, honeycombio/resource_board_test.go, honeycombio/resource_trigger_test.go
=> Fix for 'AND' filter combination causing noisy plans

client/derived_column.go, honeycombio/resource_derived_column.go, honeycombio/resource_derived_column_test.go
Handful of Derived Column improvements:
* properly escape derived column aliases
* tidy up DC client code
* add validation checks for the length of DC alias, expression, and description
=> Handful of Derived Column improvements

honeycombio/resource_board.go, honeycombio/resource_burn_alert.go, honeycombio/resource_column.go, honeycombio/resource_dataset.go, honeycombio/resource_derived_column.go, honeycombio/resource_marker.go, honeycombio/resource_query.go, honeycombio/resource_query_annotation.go, honeycombio/resource_slo.go, honeycombio/resource_trigger.go
=> refactor resource Read error checking

docs/resources/slo.md
=> adding doublequote

honeycombio/helpers_test.go, honeycombio/provider.go, honeycombio/resource_burn_alert.go, honeycombio/resource_email_recipient.go, honeycombio/resource_email_recipient_test.go, honeycombio/resource_trigger.go, honeycombio/type_helpers.go
First pass at what resource-per-type could look/would look like.
I'm pretty happy with the tradeoffs here (complexity vs boilerplatey-ness, really)
=> Email recipient resource

.github/workflows/goreleaser.yaml
Matches Hashi's example: https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.github/workflows/release.yml
=> CI: fix GPG import in release pipeline

.gitignore, client/client.go, client/column.go, client/column_test.go, docs/resources/column.md, honeycombio/resource_column.go
Adds additional fields available when working with Honeycomb Columns
=> [columns] introducing `created_at`, `updated_at` and `last_written_at`

docs/resources/burn_alert.md, docs/resources/trigger.md, honeycombio/resource_burn_alert.go, honeycombio/resource_burn_alert_test.go, honeycombio/resource_trigger.go, honeycombio/resource_trigger_test.go, honeycombio/type_helpers.go
Discovered while investigating #200
=> bugfix: infinite diff. for burn alert and trigger pagerduty recipients if severity not specified

client/board.go, client/board_test.go, docs/resources/board.md, honeycombio/resource_board.go, honeycombio/resource_board_test.go
=> boards: add support for managing column layout

client/board.go, client/board_test.go, docs/resources/board.md, example/board_with_annotations/main.tf, honeycombio/resource_board.go, honeycombio/resource_board_test.go
Closes #37 
---
- https://app.asana.com/0/0/1202770981484114
=> boards: add support for managing query graph settings

honeycombio/resource_pagerduty_recipient.go
Added the "sensative:true: flag for this opened issue: https://github.com/honeycombio/terraform-provider-honeycombio/issues/212
---
- https://app.asana.com/0/0/1202794606621599
=> added sensative flag to pagerduty receipient

docs/resources/trigger.md
This has come up a few times, so I wanted to (attempt to) clarify
=> docs: add clarifying note about Trigger time_range vs frequency

docs/resources/marker_setting.md, honeycombio/resource_marker_setting.go
=> updated color to be a required field so it matches the api client

client/dataset.go, client/dataset_test.go, docs/resources/dataset.md, honeycombio/resource_dataset.go, honeycombio/resource_dataset_test.go
I typoed a dataset description and was reminded that this bug was fixed server side but not in the provider.
=> bugfix: allow dataset resources to be updated

CHANGELOG.md, README.md, docs/index.md
Stage v0.11.1 to get out the `honeycombio_dataset` update bugfix
=> stage v0.11.1

.github/workflows/gh-issue-to-asana.yaml, .github/workflows/gh-pr-to-asana.yaml
**Which problem is this PR solving?**
https://app.asana.com/0/1198607545155957/1203451723732961/f
**Short description of the changes**
This adds 2 Github Actions to the repo to run on issue creation and PR opens/reopens. All issues become tasks and PRs become tasks if they don't have an Asana link in the description. These tasks go to our team board in the Inbox column.
=> [ci] send Github issues and PRs to Asana

CHANGELOG.md, docs/data-sources/recipient.md, honeycombio/data_source_recipient.go
- Typo fixes
"Recipients" is misspelled in a few places in the codebase and docs.
[Dictionary](https://www.merriam-webster.com/dictionary/recipient)
=> Fix typo with recipients

honeycombio/resource_board.go
Tidy up an optimistic type assertion with a guard.
- Resolves #248
=> bugfix: fix panic on board graph settings parsing

.github/workflows/gh-issue-to-asana.yaml, .github/workflows/gh-pr-to-asana.yaml
We agreed in Slack that we need a bit more info in these Asana tasks to make them useful. I have added the repo name to the task title and a link to the issue or PR at the end of the task body to meet our needs.
=> [build] add repo name and repo link to asana task

docs/resources/slo.md, honeycombio/resource_slo.go
- Closes #268 
SLIs in `__all__` are allowed to be used in an SLO in any dataset, so
update the docs for that case.
Visual inspection of docs
=> mention SLI's in __all__ in SLO `dataset` docs

.github/workflows/gh-issue-to-asana.yaml, .github/workflows/gh-pr-to-asana.yaml
=> maint: fix Asana task name creation

.github/workflows/gh-issue-to-asana.yaml
=> maint: fix Asana issue title

.github/workflows/gh-issue-to-asana.yaml, .github/workflows/gh-pr-to-asana.yaml
Includes tags to allow for easier categorization of the Asana cards created for the maintainer team to track the work
=> include tags for the asana cards created

client/column_test.go
Functionality about to be removed server side.
=> client: update column test to not rename column

go.mod, go.sum, internal/provider/trigger_resource_test.go
Fix included in terraform-plugin-framework v1.3.4 (via https://github.com/hashicorp/terraform-plugin-framework/pull/817)
- Closes #335
=> bugfix: floating point precision comparison bug

docs/data-sources/query_specification.md, docs/resources/trigger.md
Attempts to add some clarity around the relationship between a trigger's query and the frequency
=> [docs] r/trigger - add clarity around frequency

.github/workflows/apply-labels.yml
Second attempt at https://github.com/honeycombio/terraform-provider-honeycombio/pull/396 😐
=> fix: actually do the labels thing correctly

client/marker_test.go
The embedded client's Marker `List` test failed in last evening's CI run ([link](https://github.com/honeycombio/terraform-provider-honeycombio/actions/runs/8608401219/job/23590728118)).
We had a similar issue with Marker Settings `List` (#420) and a similar treatment fixed it up.
=> fix(client): unflake Marker List test

.github/workflows/validate-examples.yml, .terraformrc.local
=> fix(ci): fix validate examples

.github/CODEOWNERS
Updates CODEOWNERS to reflect an update to GitHub Team Names
=> chore(rename): update CODEOWNERS with the new name for the github team

docs/resources/query.md
Add a note to the `r/query` documentation regarding how to ensure your query is kept up to date with the latest derived column definition for any derived columns it may be referencing.
=> chore(r/query): add doc note about using latest derived column definition

client/query_spec.go
Companion to the upstream support we have now for this operator.
=> feat: add ends/does-not-end-with

honeycombio/resource_derived_column_test.go
Noticed this test was using a fixed name during another investigation.
Tidies up the test a bit as well.
=> fix(r/derived_column): tidy up test

client/burn_alert.go, client/burn_alert_test.go, docs/resources/burn_alert.md, internal/models/burn_alerts.go, internal/provider/burn_alert_resource.go, internal/provider/burn_alert_resource_test.go
Adds the ability to set and update the description on a burn alert.
=> feat: add support for burn alert description

client/recipient.go, client/recipient_test.go, docs/resources/webhook_recipient.md, internal/models/recipients.go, internal/provider/webhook_recipient_resource.go, internal/provider/webhook_recipient_resource_test.go
Support headers on the webhook recipient resource.
=> feat: webhook headers

internal/provider/query_specification_data_source.go, internal/provider/query_specification_data_source_test.go
Validation of `order` blocks was missing from `d/query_specification`, allowing the potential of apply-time errors that could have been caught during validation/planning.
=> feat(d/query_specification): 'order' validation support

client/query_spec.go, client/query_spec_test.go, docs/data-sources/query_specification.md, internal/helper/validation/valid_calculated_field.go, internal/helper/validation/valid_calculated_field_test.go, internal/models/query.go, internal/provider/query_specification_data_source.go, internal/provider/query_specification_data_source_test.go
Adds Temporary Calculated Field support.
=> feat(d/query_specification): temporary calculated field support

client/board.go, client/board_test.go, internal/provider/board_resource.go
- Breaking down my massive PR into incremental PRs
- This adds panels to board client for flexible boards support
=> feat(boards): Support panels in board client

client/board.go, client/board_test.go, docs/resources/flexible_board.md, example/flexible_board/main.tf, internal/models/flexible_board.go, internal/provider/flexible_board_resource.go, internal/provider/flexible_board_resource_test.go, internal/provider/provider.go
- Adds terraform support for Flexible boards
- create a flexible board using terraform
=> feat(boards): Add flexible board resource

client/board_test.go, docs/resources/board.md, internal/provider/board_resource.go
Marks board resource as deprecated
=> docs: Deprecate board resource in favour of flexible_board

CHANGELOG.md
=> rel: v0.36.2

client/tags.go, client/tags_test.go, internal/provider/tags.go
Increases the max length of a tag's value to 128 characters.
=> chore(tags): increase tag Value max length to 128

internal/provider/flexible_board_resource.go
- Removes limit on panel height
- Only width should be limited to 12, height is currently open to whatever positive number the user sets
=> fix(r/flexible_board): Remove height limit

CHANGELOG.md
=> rel: v0.40.1

CHANGELOG.md, README.md, docs/index.md
=> rel: v0.41.0
