honeycombio/terraform-provider-honeycombio

docs/data-sources/trigger_recipient.md
honeycombio/data_source_query.go
honeycombio/resource_column.go
honeycombio/resource_derived_column.go

Depends on https://github.com/kvrhdn/go-honeycombio/pull/16
* Minor documentation fix
* Fixes column read/updating (it wasn't saving the ID)
* Checks if column exists before creating (fixes #59)
* Fixes query filter `value_boolean` so you can specify false and it won't ignore it

Better columns, support board query annotations

---

.github/workflows/ci.yaml
.github/workflows/goreleaser.yaml
CONTRIBUTING.md
README.md
client/client_test.go
client/dataset_test.go
honeycombio/data_source_datasets_test.go
honeycombio/resource_board_test.go
scripts/setup-testsuite-dataset

Test suite is now decoupled from original dataset used for testing, keys updated to use an Internal test team, and initial pass on the markdown files done to update `kvrhdn/terraform-provider-honeycombio` -> `honeycombio/terraform-provider-honeycombio`

Restore CI functionality after project transfer

---

client/trigger.go
client/trigger_test.go
docs/data-sources/query_specification.md
docs/data-sources/trigger_recipient.md
docs/resources/board.md
docs/resources/query.md
docs/resources/query_annotation.md
docs/resources/trigger.md
example/board/main.tf
example/trigger/main.tf
example/trigger_with_slack_recipient/main.tf
honeycombio/data_source_query_specification.go
honeycombio/data_source_query_specification_test.go
honeycombio/internal/verify/json.go
honeycombio/provider.go
honeycombio/resource_board.go
honeycombio/resource_board_test.go
honeycombio/resource_query.go
honeycombio/resource_query_annotation_test.go
honeycombio/resource_query_test.go
honeycombio/resource_trigger.go
honeycombio/resource_trigger_test.go

As discussed in #96, Triggers and Boards now require Query IDs instead of JSON.

Require Query IDs over inline query JSON

---

docs/data-sources/query_specification.md
docs/data-sources/trigger_recipient.md
docs/resources/board.md
docs/resources/query.md
docs/resources/query_annotation.md
docs/resources/trigger.md
example/board/main.tf
example/trigger/main.tf
example/trigger_with_slack_recipient/main.tf
honeycombio/data_source_query_specification.go
honeycombio/data_source_query_specification_test.go
honeycombio/provider.go
honeycombio/resource_board_test.go
honeycombio/resource_query_annotation_test.go
honeycombio/resource_query_test.go
honeycombio/resource_trigger_test.go

The new name more accurately reflects what the data source is used for.
Breaking change as outlined in #96
Resolves #65

rename query datasource to query_specification

---

client/query_spec.go
client/query_spec_test.go
client/type_helpers.go
docs/data-sources/query_specification.md
honeycombio/data_source_query_specification.go
honeycombio/data_source_query_specification_test.go
honeycombio/resource_column_test.go
honeycombio/type_helpers.go

Adds support for "havings". Snuck in a few linter fixes as well 🙃 
Resolves #97

HAVING support

---

client/query_spec.go
client/query_spec_test.go
docs/data-sources/query_specification.md
honeycombio/data_source_query_specification.go
honeycombio/data_source_query_specification_test.go

Adds support for the `CONCURRENCY` operator.
Resolves #108

Add CONCURRENCY operator support to Query Specification

---

client/query_spec.go
client/query_spec_test.go
docs/data-sources/query_specification.md
honeycombio/data_source_query_specification.go
honeycombio/data_source_query_specification_test.go
honeycombio/resource_board_test.go
honeycombio/resource_query_test.go
honeycombio/type_helpers.go
honeycombio/type_helpers_test.go

After some testing with curl, it seemed if we properly parse-and-coerce the HCL-read string value that this would work fine without the type-specific `value_*` filter options while solving #102 in a round about fashion (and providing a much cleaner interface and nicer DX).
This also un-depreciates the filter's `value` while depreciating all of the `value_*` fields introduced by #29.

Fix filter value type parsing and depreciate value_* fields

---

client/derived_column_test.go
honeycombio/resource_derived_column.go

Today, we broke a whole slew of triggers because we inadvertently changed the definition of a derived column by creating a new `honeycombio_derived_column` resource with an already in-use alias.
This should not be possible according to the Honeycomb API:
```
❯ curl https://api.honeycomb.io/1/derived_columns/test-dataset \
-X POST \
-H "X-Honeycomb-Team: REDACTED" \
-d '{"alias": "liz-test", "expression": "MAX(1)", "description": "liz testing if you can unintentionally overwrite derived columns"}'
{"id":"123456","expression":"MAX(1)","alias":"liz-test","description":"liz testing if you can unintentionally overwrite derived columns"}
~
❯ curl https://api.honeycomb.io/1/derived_columns/test-dataset \
-X POST \
-H "X-Honeycomb-Team: REDACTED" \
-d '{"alias": "liz-test", "expression": …
```

Do not update an existing derived column with creation of new TF resource

---

main.go

Allow debugging with delve or an IDE's debugger by passing the `-debug` flag on start:
https://www.terraform.io/plugin/sdkv2/debugging#debugger-based-debugging

Allow provider debugging

---

.vscode/launch.json
honeycombio/resource_trigger.go
honeycombio/resource_trigger_test.go

This addresses unstable recipient ordering which cannot be mitigated using a DiffSupressFunc (see: https://github.com/hashicorp/terraform-plugin-sdk/issues/477).
Fix inspired by https://github.com/linode/terraform-provider-linode/pull/386
Should resolve #123

Fix Trigger recipient ordering resulting in infinite diffs

---

.github/workflows/ci.yaml
.github/workflows/goreleaser.yaml
go.mod

Terraform Plugin SDK v2.14.0 mentions 1.17 as the supported go version. I didn't want to jump right to 1.18 as TF core won't be built with it until 1.2.0

Update to Go v1.17

---

honeycombio/resource_board.go
honeycombio/resource_column.go
honeycombio/resource_dataset.go
honeycombio/resource_query_annotation.go

Fix Query Annotation name max. length (had misread it to be equal to a Trigger), and add additional checks for some Board, Column, and Dataset fields.

Additional field length validation tests

---

client/trigger.go
client/trigger_test.go
docs/resources/trigger.md
honeycombio/resource_trigger.go
honeycombio/resource_trigger_test.go

Adding a new attribute to Triggers, it will include the following changes:
- adding a new alert frequency to the Trigger structure
The current behaviors of triggers is an alert is sent on change. We are adding a the feature for the provider set alert on true for our triggers.
Read more about alert frequency here:
https://docs.honeycomb.io/working-with-your-data/triggers/#configuration
---
- https://app.asana.com/0/0/1202136190006122

[triggers] Add alert_type field for Triggers

---

docs/resources/burn_alert.md

Burn alerts are required to have at least one recipient, but the docs mention having "zero or more."
The provider/api validation prevents zero recipients with `Error: Insufficient recipient blocks`.

Update burn alert docs to match validation

---

client/recipient.go

Has already been removed from upstream API

client: remove 'zenoss' recipient type

---

docs/resources/email_recipient.md
docs/resources/pagerduty_recipient.md
docs/resources/slack_recipient.md
docs/resources/webhook_recipient.md

Noticed I forgot to add the `Import` section to the new email recipient docs

docs: add missing import section to new recipient resources

---

client/recipient.go
docs/resources/burn_alert.md
docs/resources/trigger.md
honeycombio/resource_burn_alert.go
honeycombio/resource_burn_alert_test.go
honeycombio/resource_trigger.go
honeycombio/resource_trigger_test.go
honeycombio/type_helpers.go

BurnAlerts and Triggers will now be able to optionally pass a severity level to PagerDuty when a notification is sent.
---
- https://app.asana.com/0/0/1202483433776325

Adds severity support for PagerDuty notifications

---

.github/workflows/ci.yaml

Noticed only one of the two files was being processed. Tipped off by https://github.com/codecov/codecov-action/issues/325 that allowing automatic detection fixed their use and it appears to here as well?!

CI: fix code coverage

---

client/dataset.go
client/dataset_test.go
docs/resources/dataset.md
honeycombio/resource_dataset.go

Adds additional fields available when working with a Honeycomb Dataset

[dataset] introducing `created_at` and `last_written_at`

---

go.mod
honeycombio/provider.go

This removes the attempt at logging a warning, but I couldn't get tflog to play nicely anyway

provider: fix crash on startup when HONEYCOMB_API_KEY env var isn't present

---

honeycombio/data_source_query_specification.go
honeycombio/data_source_query_specification_test.go

A `honeycombio_query_specification` without a `calculation` will get the default calculation (`COUNT`) returned by the API but cause an infinite diff for resources relying on the JSON input (e.g. `honeycombio_query`).
This resolves this issue, while also marking the `json` attribute of the data source read-only as indicated by the Terraform Plugin SDK documentation.

bugfix: missing 'calculation' in Query Specification can cause infinite diff

---

honeycombio/resource_column.go

Omitting the optional `type` argument in the `honeycombio_column` resource will cause infinite diff.
Discovered while validating another bug 🙃

bugfix: missing 'type' in column resource can cause infinite diff

---

client/board_test.go
client/column_test.go
client/query_result_test.go
client/query_spec.go
client/query_spec_test.go
client/query_test.go
client/trigger_test.go
client/type_helpers.go
client/type_helpers_test.go
honeycombio/data_source_query_specification.go
honeycombio/internal/verify/query_spec.go
honeycombio/resource_column.go
honeycombio/resource_query.go
honeycombio/resource_query_test.go
honeycombio/type_helpers.go

- Closes #233 
Adds the concept of equivalent (but not strictly equal) QuerySpecs to be used to suppress diffs (e.g. filters or havings in a different order).
Also, sneaks in a `ToPtr` typed function and removes all the specific `Ptr` functions (e.g. `StringPtr`, `BoolPtr`).

query_spec - add 'equivalence' to suppress diffs

---

honeycombio/data_source_recipient.go

Fixes a bug in the `honeycombio_recipient` data source where only supplying `type` will error even if there was _only_ one Recipient of that type in the Team.
Example:
```hcl
data "honeycombio_recipient" "test" {
type = "email"
}
output "value" {
value = data.honeycombio_recipient.test.id
}
```
The above will error with the current version of the provider even with exactly one Recipient of type email existing in the Team.

recipient datasource - fix bug where only supplying 'type' would error

---

docs/resources/column.md
honeycombio/resource_column.go
honeycombio/resource_column_test.go

Using 'key_name' felt like we were leaking an API abstraction into the resource needlessly.
This PR also removes a surprising behavior in the column resource where an existing column would silently be used on create instead of erroring.

column: deprecate 'key_name' in favor of 'name'

---

OSSMETADATA
README.md

Noticed we didn't have the OSS lifecycle properly setup for this project.
Also removes the 'Go Report Card' badge 🤷🏻

README: add missing OSS Lifecycle badge

---

docs/resources/board.md

Noticed this while validating a bug.

docs: board - remove deprecated 'dataset' from simple board example

---

.github/workflows/gh-pr-to-asana.yaml

This change updates the PR to Asana workflow to run on pull_request_target events so it can work on PRs from forks. This should subvert the need to approve the workflow to run and allow the workflow to access the necessary secrets.

[ci] update workflow to work for pull_request_target

---

README.md

The general description includes multiple sections which were rendering in a single line instead of multiple lines because of the missing line in-between
before
after

docs: fix README.md markdown rendering

---

client/board.go
client/board_test.go
docs/resources/board.md
honeycombio/resource_board.go

Co-authored-by: Jason Harley <jason@honeycomb.io>
Signed-off-by: Davin Taddeo <davin@honeycomb.io>
Adds the new `board_url` output from the Boards API when returning a board create or get action

Add board_url link to the board resource output

---

CHANGELOG.md

Missed this while preparing the release. Already updated the [GH Release](https://github.com/honeycombio/terraform-provider-honeycombio/releases/tag/v0.12.0)

CHANGELOG: addendum to the 0.12.0 release notes

---

docs/resources/column.md
honeycombio/resource_column.go
honeycombio/resource_column_test.go

Since the provider's inception this resource treated deletes as a 'noop' -- simply removing the column from state.
In 0.12.0 we removed the silent import of an existing column on create which has forced this gap into the light.
Given that column deletes are fully supported in the API, it felt proper to enable them here as it is assumed that the operator understands that there is removal.
---
- https://app.asana.com/0/0/1203644387911130

honeycombio_column: delete column on destroy

---

docs/resources/query.md

The `dataset = %s` was a typo.

correct dataset in honeycombio_query example

---

docs/resources/trigger.md

- Closes #271 
When you use the example code in `honeycombio_trigger`'s documentation,
it will fail at time of `terraform apply`.
The error returned from the Honeycomb API says that the query duration
can't be more than 4x greater than the trigger's frequency.
The default time_range on `honeycombio_query_specification` is 7200
which is 12x larger than the `frequency` on `honeycombio_trigger`.
An alternative fix would be to change the `frequency` setting, instead.
I'd be willing to go that route, and produce another PR! It felt like
maybe it's worth mentioning the `time_range` value explicitly here, but
I'm not convinced on that.
Another possible change would be to change the default `time_range`, but
that would be a breaking change. Not only because of user expectations
but also because …

correct time_range in honeycombio_trigger example

---

client/board_test.go
client/query_spec.go
client/query_spec_test.go
client/type_helpers.go
honeycombio/data_source_query_specification.go
honeycombio/resource_query_test.go

- Closes #275
The QuerySpec 'equivalence' functionality introduced in #236 to suppress diffs failed to detect changes in `time_range`, `filter_combination`, and `calculation`.

bugfix: query equivalence for time_range, filter ops, and calculations

---

client/marker_test.go

The client's Marker test suite has failed a few times on a time comparison test ([most recent example](https://github.com/honeycombio/terraform-provider-honeycombio/actions/runs/4458036388/jobs/7829506246)).
This fixes that up ✨

fix - marker client test flake

---

client/board.go
docs/resources/board.md
honeycombio/resource_board.go

You can't set a query to display with overlaid aggregates on a board without access to the right graph settings.
Adds the overlaid_charts graph setting that is supported by the API
Configure a board with the overlaid charts option and verify that that is reflected in Honeycomb

Add overlaid charts support

---

docs/resources/dataset.md
honeycombio/resource_dataset.go
honeycombio/resource_dataset_test.go

- Closes #290 
Adds import support for `honeycombio_dataset`. Now that the resource supports managing `description` and `expand_json_depth` this feels like a more natural Terraform experience.

honeycombio_dataset: add import support

---

client/burn_alert_test.go
client/client.go
client/dataset_definitions_test.go
client/dataset_test.go
client/slo_test.go

There were a handful of linter warnings and this fixes or suppresses them all to allow any new ones to be more obvious.

appease the linter gods

---

client/column.go
docs/data-sources/column.md
docs/data-sources/columns.md
example/column_sync/main.tf
example/columns_conditional_create/main.tf
honeycombio/data_source_column.go
honeycombio/data_source_column_test.go
honeycombio/data_source_columns.go
honeycombio/data_source_columns_test.go
honeycombio/provider.go

- Closes #42 
This PR adds a minimal implementation for the `honeycombio_column` and `honeycombio_columns` data sources
after running `make install_macos`,  try out the following TF for fun:
```hcl
data "honeycombio_columns" "all" {
dataset = var.required_columns_dataset_name
}
data "honeycombio_column" "all" {
for_each = toset(data.honeycombio_columns.all.names)
dataset = var.required_columns_dataset_name
name    = each.key
}
data "honeycombio_column" "mycol" {
dataset = var.required_columns_dataset_name
name    = "db.type"
}
resource "honeycombio_column" "othercol" {
dataset     = var.required_columns_dataset_name
name        = "othercol"
type        = data.honeycombio_column.mycol.type
description = data.honeycombio_column.mycol.description
hidden      = …
```

Add honeycombio_column and columns data sources

---

go.mod
go.sum
honeycombio/provider.go
honeycombio/resource_trigger_test.go
internal/helper/type_strings.go
internal/helper/validation/divisible_by.go
internal/helper/validation/divisible_by_test.go
internal/models/triggers.go
internal/provider/derived_column_data_source_test.go
internal/provider/derived_columns_data_source_test.go
internal/provider/provider.go
internal/provider/provider_test.go
internal/provider/trigger_resource.go
internal/provider/trigger_resource_test.go

First pass at migrating the resource: with this (verbose) groundwork laid the test suite can be fleshed out and the open bugs squashed 🤞🏻 
The current SDKv2 based Trigger resource is being left in place (and its tests skipped) just not wired up for use.

migrate honeycombio_trigger resource 'as is' to Plugin Framework

---

.github/workflows/ci.yaml
client/recipient.go
honeycombio/data_source_column_test.go
honeycombio/data_source_columns_test.go
internal/helper/modifiers/notification_recipients.go
internal/provider/derived_column_data_source_test.go
internal/provider/trigger_resource.go
internal/provider/trigger_resource_test.go

This completes the move of the `honeycombio_trigger` resource to the Terraform Plugin Framework (started in #306).
In order to support versions of Terraform core older than 1.4.0 (which, is rather "fresh") there is a bit of logic to handle `Null` or `Unknown` values of these awkwardly-shaped notification recipients.
This also 'bumps' the version of Terraform core used in CI to 1.0.11 (from the old 0.14.x series).
- Closes #303, #267, #200
---
- https://app.asana.com/0/0/1204716790924151

Trigger recipient fixes

---

.goreleaser.yaml

Properly set the provider version on release
Introduced by: #305

[goreleaser] fix regression and set version on released artifact

---

internal/provider/trigger_resource.go
internal/provider/trigger_resource_test.go

Fixes the currently known pair of panics on the `honeycombio_trigger` resource by relying on config vs plan as the source of what to persist to state.
- Resolves #309
- Replaces #331

bugfix - resolve trigger recipient panics by relying on config vs plan

---

client/recipient_test.go

Last evening's scheduled CI run failed with a flakey time comparison in the client's Recipient test suite ([link](https://github.com/honeycombio/terraform-provider-honeycombio/actions/runs/5815456677/job/15767051455)).
This fixes that to avoid future failures and tidies things up a bit since I was in there.

fix: client - flakey recipient time comparison test

---

docs/data-sources/recipients.md
docs/data-sources/slo.md
docs/data-sources/slos.md
honeycombio/data_source_columns.go
honeycombio/data_source_datasets.go
honeycombio/data_source_recipients.go
internal/helper/filter/slo_filter.go
internal/helper/hashcode/hashcode.go
internal/helper/ptr.go
internal/helper/validation/valid_regex.go
internal/helper/validation/valid_regex_test.go
internal/provider/derived_column_data_source.go
internal/provider/derived_columns_data_source.go
internal/provider/provider.go
internal/provider/slo_data_source.go
internal/provider/slo_data_source_test.go
internal/provider/slos_data_source.go
internal/provider/slos_data_source_test.go

Adds a pair of datasources for SLOs: `honeycombio_slo` and `honeycombio_slos`.
Tidies up docs in a few places as well.
- Closes #332

Add SLO datasources

---

client/auth.go
client/auth_test.go
client/client.go
client/client_test.go
docs/data-sources/auth_metadata.md
internal/provider/auth_metadata_data_source.go
internal/provider/auth_metadata_data_source_test.go
internal/provider/provider.go

Adds new data source `honeycombio_auth_metadata` to enable pulling Authorization, Environment, or Team into Terraform configurations.
- Closes #247

Add auth metadata data source

---

docs/data-sources/auth_metadata.md

Missing leading `data.` in the example

datasource/honeycombio_auth_metadata - doc fix

---

client/marker_test.go

The client's test suite had a flakey error over the weekend ([link](https://github.com/honeycombio/terraform-provider-honeycombio/actions/runs/6140767105/job/16660172811)) during a nightly CI run.
This should keep that error from happening again.

client - fix Marker test flake

---

.github/dependabot.yaml
.github/release.yml

Enable some ✨ fancy ✨ GitHub features to help maintenance and release activities:
1. dependabot: group HashiCorp Go library updates together when possible
1. setup an initial `.github/release.yml` to help get CHANGELOG updates closer to the right format automatically

github automation improvements

---

docs/data-sources/query_result.md
docs/resources/derived_column.md
docs/resources/marker.md
docs/resources/marker_setting.md
docs/resources/query.md
docs/resources/query_annotation.md

I had thought this was already done, but it clearly was not.
Noticed as a result of a [Pollinators question](https://honeycombpollinators.slack.com/archives/C4T3A32CX/p1696876673180979).

[docs] add environment-wide '__all__' note where supported

---

.github/workflows/goreleaser.yaml

While trying to release v0.18.0 we got a new permissions error during the "release workflow" ([link](https://github.com/honeycombio/terraform-provider-honeycombio/actions/runs/6487306414/job/17617320152)):
> error=scm releases: failed to publish artifacts: could not release: POST https://api.github.com/repos/honeycombio/terraform-provider-honeycombio/releases: 403 Resource not accessible by integration []
Looking at some similar errors, we think goreleaser may (now?) require increased permissions to create a draft release ([reference](https://github.com/goreleaser/goreleaser/issues/2642))

ci: fix release workflow

---

.github/workflows/goreleaser.yaml

After #375 unblocked us to release v0.18.0, I discovered that a similar change had made it's way into the provider [scaffolding framework release](https://github.com/hashicorp/terraform-provider-scaffolding-framework/blob/main/.github/workflows/release.yml) workflow.
This updates our workflow to more or less match the scaffolding project's suggested.

ci: update release workflow to suggested

---

honeycombio/resource_derived_column_test.go
honeycombio/type_helpers.go

SDKv2 based resources reporting errors that weren't complete RFC7807-style errors reported something like the following:
> Error: Empty Summary: This is always a bug in the provider and should be reported to the provider developers.
This fixes that by always ensuring that "Summary" is set.

bugfix: ensure Summary is set on SDK v2 Diagnostics

---

client/recipient.go
client/recipient_test.go
docs/data-sources/recipient.md
docs/data-sources/recipients.md
docs/resources/burn_alert.md
docs/resources/msteams_recipient.md
docs/resources/trigger.md
honeycombio/data_source_recipient.go
honeycombio/data_source_recipient_test.go
honeycombio/data_source_recipients.go
honeycombio/provider.go
honeycombio/resource_msteams_recipient.go
honeycombio/resource_recipients_test.go
honeycombio/type_helpers.go
internal/provider/burn_alert_resource.go
internal/provider/notification_recipients.go
internal/provider/trigger_resource.go

Adds supports for `msteams` recipients.
Also fixes a "sneaky bug" where a previous refactor would allow `marker` type recipients on Burn Alerts during the validation stage (the API still would reject them).
---
- https://app.asana.com/0/0/1205887299919797

Add support for 'msteams' recipients

---

client/errors.go
client/errors_test.go

This PR fixes a bug where the errors returned from the client weren't showing the impacted field and weren't getting separated when there were multiple errors associated with 1 request. This made any server-side errors a little difficult to read/fix.
I'm not super familiar with all the different forms the Details section of DetailedError can take, so if there are checks I can remove, please let me know. 
Pre-requisites:
- You'll need Go 1.20 and the latest Terraform installed.
- You'll need a team in Honeycomb to test against.
- You'll need a dataset, derived column, and SLO for that team.
- You'll need an API key for that team.
1. Create a new directory called `providers` somewhere you can easily access (but not inside the same folder as your Terraform config).
1. Build the provider by …

client: Fix bug where API errors weren't including the field or getting separated

---

.github/workflows/apply-labels.yml

Pulls in the label management action from https://github.com/honeycombio/oss-management/tree/v1/labels

chore: add GH action for standardized labels

---

client/errors.go
honeycombio/resource_slo.go
honeycombio/resource_slo_test.go
internal/provider/burn_alert_resource.go
internal/provider/burn_alert_resource_test.go
internal/provider/trigger_resource.go

v0.19.0's client re-write introduced new client error handling but mishandled the classic "re-create when missing remotely" behaviour that Terraform in known -- and loved -- for.
The TL;DR for the fix is that pointers to errors and `errors.As()` are not a good mix for successful error checking.
Initially reported as a bug via Honeycomb Support.

fix(slo, burn_alert, client) missing resources shouldn't error but be recreated

---

client/auth_test.go
client/board_test.go
client/burn_alert_test.go
client/client_test.go
client/column_test.go
client/dataset_definitions.go
client/dataset_definitions_test.go
client/dataset_test.go
client/derived_column_test.go
client/errors_test.go
client/marker_settings_test.go
client/marker_test.go
client/query_annotation_test.go
client/query_result_test.go
client/query_spec_test.go
client/query_test.go
client/recipient_test.go
client/slo_test.go
client/trigger_test.go
client/type_helpers_test.go
honeycombio/resource_dataset_definition_test.go
internal/helper/test/strings.go

First step toward removing the dependency on `scripts/setup-testsuite-dataset` and also not being in a position that some failed test runs cause subsequent runs to fail due to conflicts.
In addition to randomly generating strings, the idea is to prefix the things we create with `test.` and make email addresses in the `@example.com` domain so that we can in future make use of [Sweepers](https://developer.hashicorp.com/terraform/plugin/testing/acceptance-tests/sweepers) to remove anything starting with `test.` or in the `@example.com` domain.
More to improve here, but this was intended to be a "time boxed" first pass.

chore: first pass at moving away from pre-created columns

---

client/board.go
honeycombio/resource_board.go
honeycombio/resource_board_test.go

When removing a setting from `graph_settings` the value is not reverted to "false" (the documented default).
During testing #399 was discovered but I believe the fix there is to re-implement the resource in the Plugin Framework.
Initially reported via Honeycomb Support.
---
- https://app.asana.com/0/0/1205951498507418

fix(honeycombio_board) graph_settings should revert to false when removed

---

client/query_spec.go
client/query_spec_test.go

Reported via Pollinators ([link](https://honeycombpollinators.slack.com/archives/C017T9FFT0D/p1700814782578459)).
The Query Builder will export JSON query specs with `"granularity": 0`, but the API will not return this field if it's set to zero. This marks either case as equivalent.
Prior to this change a `honeycombio_query` as below would cause an infinite diff:
```hcl
resource "honeycombio_query" "test" {
dataset    = var.dataset
query_json = <<-EOF
{
"breakdowns": ["app.tenant"],
"calculations": [{ "op": "COUNT" }],
"orders": [
{
"column": "app.tenant",
"order": "ascending"
}
],
"granularity": 0
"filter_combination": "AND",
}
EOF
}
```
Plan output:
```
-/+ resource "honeycombio_query" "test" {
~ id         = "AD1Ue8TJCfC" -> (known after apply)
~ query_json = jsonencode(
~ {
+ …
```

fix(client) - queryspec Granularity equivalency

---

docs/data-sources/query_specification.md
honeycombio/data_source_query_specification.go

Updates the note about `in` and `not-in` to reference `value` instead of `value_string` (which is deprecated) as well as a couple other cleanups related to the move to `value`

docs: cleanup value_string reference

---

client/client.go

- Closes #410 
Removes extra underscore in the legacy API key so it will start working again

fix: legacy api key typo

---

README.md
client/client.go
docs/index.md
internal/provider/burn_alert_resource_test.go
internal/provider/trigger_resource_test.go

This switches the -- previously undocumented -- API Endpoint envvar to the more standard `HONEYCOMB_API_ENDPOINT` and documents it along with specific instructions on how to use the provider with Honeycomb EU.
This is technically a breaking change (even though the envvar was undocumented) and will need to be called out as such in the release notes

feat(client): standardize and document API endpoint envvar

---

client/marker_settings_test.go

The embedded client's Marker Settings test suite flaked last evening ([link](https://github.com/honeycombio/terraform-provider-honeycombio/actions/runs/7563515384/job/20596094329)) during the nightly smoke test run.
This should hopefully prevent that from happening again in future.

fix(client): fix Marker Settings flakey test

---

honeycombio/provider.go
internal/provider/provider.go

Noticed that the API configuration envvar was not mentioned in these inline docs.

fix(docs): add missing mention to HONEYCOMB_API_ENDPOINT env var for endpoint configuration

---

client/query_spec.go
client/query_spec_test.go

Reported via Pollinators ([link](https://honeycombpollinators.slack.com/archives/C017T9FFT0D/p1705836614190879)).
If `breakdowns` is provided as an empty slice DeepEqual fails to view that as equal to a queryspec without the slice defined ([]string string vs []string nil).
Adds an empty list of `orders` to be sure it didn't have a similar issue, but it pass the empty equivalence test fine.

fix(client): fix queryspec equivalence for empty breakdowns

---

internal/provider/burn_alert_resource.go
internal/provider/burn_alert_resource_test.go
internal/provider/notification_recipients.go
internal/provider/notification_recipients_test.go
internal/provider/trigger_resource.go
internal/provider/trigger_resource_test.go

If a recipient was updated outside of Terraform (i.e. the UI or via the API in some other way) the provider would get rather cranky and spit out an error like:
> Could not find Recipient xysef83ryH in state
This adjusts that behaviour to instead accept that the recipient is defined remotely and allow the rest of Terraform's diffing process to handle the difference and present that plan to the user.
Effects `r/burn_alert` and `r/trigger`
---
- https://app.asana.com/0/0/1206583960682330

fix(recipients): better handle the case where a recipient is modified outside of Terraform

---

.github/workflows/ci.yaml

The upgrade to v4 of the codecov action broke "tokenless uploads".
This fixes that, while continuing to not fail CI if we can't upload, as it's a nice-but-not-gating metric to continue to track.

fix(ci): fix codecov after v4 upgrade

---

client/client_test.go
honeycombio/resource_column.go
honeycombio/resource_derived_column.go
honeycombio/resource_slo.go
internal/provider/burn_alert_resource.go
internal/provider/trigger_resource.go

Some columns and derived columns have slashes in the name. Prior to this change, trying to import either with slashes in the name would result in a message like:
```shell
$ terraform import 'honeycombio_column.test' 'test/my/column/name'
honeycombio_column.test: Importing from ID "test/my/column/name"...
honeycombio_column.test: Import prepared!
Prepared honeycombio_column for import
honeycombio_column.test: Refreshing state... [id=test/my/column/name]
╷
│ Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to "honeycombio_column.test", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that the id is correct
│ and that it is associated with the provider's configured region or …
```

fix: handle column and derived column imports with slashes in the name

---

honeycombio/data_source_query_specification.go
honeycombio/data_source_query_specification_test.go

`in`, and `not-in` filter values should always be treated as an array. This allows for the possibility of filters like `app.mything.id not-in 38374`

fix: query specification - always treat 'in','not-in' filter values as an array

---

internal/models/burn_alerts.go
internal/models/notification_recipients.go
internal/models/triggers.go
internal/provider/burn_alert_resource.go
internal/provider/burn_alert_resource_test.go
internal/provider/notification_recipients.go
internal/provider/notification_recipients_test.go
internal/provider/trigger_resource.go

- Closes #434 
Migrates `NotificationRecipients` to `types.Set` and `NotificationRecipientDetails` to `types.List` instead of slices.
---
- https://app.asana.com/0/0/1206682900457198

fix(recipients): dynamic block bug

---

.github/dependabot.yaml

Matches internal conventional commit standard

chore: update dependabot commit message prefix

---

.github/workflows/ci.yaml
scripts/setup-testsuite-dataset

This duplicates the existing integration test setup to run against our newer EU infrastructure.
I created a Terraform Provider team in the EU region and configured the testacc setup and tests in the Action to take the honeycomb api endpoint as an env var.
You can see the integration tests successfully ran in US and EU on this PR.
---
- https://app.asana.com/0/0/1205935108176450

ci: add eu integration test flow

---

.github/workflows/ci.yaml

Now that golanglint-ci action has been upgraded to 5.x (#466) we can re-enable the setup-go's management of the build cache.

maint(ci): setup-go - re-enable cache

---

client/query_spec.go
honeycombio/data_source_query_specification_test.go
honeycombio/helpers_test.go

Currently, this happens: 
1. Import a query resource, like:
```
import {
id = "system_stats/abc123"
to = honeycombio_query.kafka_disk_usage
}
```
2. You get this, which is technically correct, but a bit ugly, and will upset pickier linters:
```
❯ cat generated_resources.tf
resource "honeycombio_query" "kafka_disk_usage" {
dataset    = "system_stats"
query_json = "{\n  \"calculations\": [\n    {\n      \"op\": \"MIN\",\n      \"column\": \"disk_percent_free\"\n    }\n  ],\n  \"filters\": [\n    {\n      \"column\": \"host_group\",\n      \"op\": \"=\",\n      \"value\": \"kafka\"\n    },\n    {\n      \"column\": \"environment\",\n      \"op\": \"=\",\n      \"value\": \"dogfood\"\n    }\n  ],\n  \"breakdowns\": [\n    \"hostname\"\n  ],\n  \"orders\": [\n    {\n      \"op\": \"MIN\",\n …
```

fix(query): clean up generated queryspec output

---

client/board.go
client/board_test.go
docs/resources/board.md
honeycombio/resource_board.go
honeycombio/resource_board_test.go
internal/provider/slos_data_source_test.go

Adds support to place SLOs on boards.
Following the board's existing `query {}` blocks, this adds `slo {}` and takes an ID.
SLOs on Board are under active development and do not yet have an order but are visually displayed by their creation date. Future releases will support ordered placement.

r/board: add SLO support

---

client/trigger.go
docs/resources/trigger.md
internal/models/triggers.go
internal/provider/trigger_resource.go
internal/provider/trigger_resource_test.go

In [v0.2.0](https://github.com/honeycombio/terraform-provider-honeycombio/blob/main/CHANGELOG.md#020-jan-27-2022) we dropped `query_json` from `r/trigger` to smooth out few a gnarly bugs associated with the Plugin SDK. With that change the ability to more deeply validate that a Trigger's query met the requirements was sadly lost.
Since then, `r/trigger` has been re-written in the new Plugin Framework and with it we got the ability to determine if the configuration was building via Query ID or Query JSON. This change takes advantage of that ability and re-introduces deeper validation for Trigger query's so long as you use `query_json` in place of `query_id`

r/trigger: re-introduce query_json for deeper validation

---

.github/workflows/goreleaser.yaml

Just encountered an error trying to release v0.24.0 ([link](https://github.com/honeycombio/terraform-provider-honeycombio/actions/runs/9518838459/job/26240664325)).
Downgrading go-releaser to get this out the door.
Related: https://github.com/goreleaser/goreleaser/issues/4914

fix(ci): downgrade go-releaser

---

client/client.go

Received a report of a panic during apply (#490).
My best guess looking at the stack trace is that the response was not able to get created and made its way into `retryHTTPCheck` as `nil`. This should guard against that in future.
- Closes #490

fix: client - guard against nil resp during retry check

---

honeycombio/type_helpers.go
honeycombio/type_helpers_test.go

Issue flagged by CodeQL.
- Closes #499

fix: incorrect conversion between integer types

---

client/v2/api_keys_test.go
client/v2/client.go
client/v2/environments.go
client/v2/environments_test.go
client/v2/models.go
docs/data-sources/environment.md
docs/data-sources/environments.md
docs/data-sources/slo.md
docs/resources/environment.md
internal/helper/filter/detail_filter.go
internal/helper/modifiers/deletion_protection.go
internal/models/detail_filter.go
internal/models/environments.go
internal/models/slo.go
internal/provider/api_key_resource.go
internal/provider/detail_filter.go
internal/provider/environment_data_source.go
internal/provider/environment_data_source_test.go
internal/provider/environment_resource.go
internal/provider/environment_resource_test.go
internal/provider/environments_data_source.go
internal/provider/environments_data_source_test.go
internal/provider/provider.go
internal/provider/slo_data_source.go
internal/provider/slo_data_source_test.go
internal/provider/slos_data_source.go

Adds the ability to manage a team's Environments ✨ by introducing a pair of data sources and a shiny new resource.
---
- https://app.asana.com/0/0/1207759682365320

feat: environment management support

---

.github/workflows/ci.yaml
client/v2/api_keys_test.go
client/v2/client_test.go
internal/provider/api_key_resource_test.go
internal/provider/environment_data_source_test.go
internal/provider/environments_data_source_test.go
internal/provider/provider_test.go

A follow-up to #501 and #496, this cleans up the various environment-related TODOs.

chore: cleanup static environment ID in favour of new functionality

---

honeycombio/resource_dataset_definition.go
honeycombio/resource_dataset_definition_test.go
scripts/setup-testsuite-dataset

Fixes a null pointer panic when TF tries to refresh a dataset definition that's been removed. In this case, `extractDatasetDefinitionColumnByName` returns `nil` (ie, the API returned a `null` for that definition), which needs to be handled.
- Closes #504

fix: read of null definition causes panic (#504)

---

honeycombio/resource_slo.go

- Closes #<enter issue here>
Note: Happy to make an issue if this is deemed appropriate for this change.
Reflect OpenAPI validation of SLO's TargetPPM, here: https://docs.honeycomb.io/api/tag/SLOs#operation/createSlo!path=target_per_million&t=request
SLO resources should no longer fail when creating an SLO with TargetPPM less than 1%.
I didn't see any existing automation regarding validation - happy to add some if it's critical for this change. 
* I did run this PR against existing automation, per repo instructions. 
* I got a couple errors, but I think they're mostly just environment related rather than fix related.
```
λ gotestsum --format-hide-empty-pkg ./... -- -p1 -count=1
✓  internal/helper (491ms)
✓  internal/helper/validation (664ms)
✓  client (2.846s)
✓  client/v2 (33.387s)
✖ …
```

fix(slos): Reflect OpenAPI validation of SLOs

---

internal/provider/query_resource_test.go

`TestAcc_QueryResourceUpgradeFromVersion022` starting failing seemingly out of nowhere during the nightly Jul 26 CI "smoke test" ([link](https://github.com/honeycombio/terraform-provider-honeycombio/actions/runs/10119289412)) with the following error:
> === NAME  TestAcc_QueryResourceUpgradeFromVersion022
query_resource_test.go:118: Error retrieving state, there may be dangling resources: exit status 1
Failed to marshal state to json: unsupported attribute "value_boolean"
This test is (was?) helpful in testing the migration from the Plugin SDK to the Plugin Framework and while it'd be nice to keep it running it isn't crucial at the moment.
Will investigate why this is happening and try to remediate, but restoring CI runs is more important at the moment.

fix: temporarily disable broken r/query test

---

.github/workflows/ci.yaml

Limit integration test runs with [concurrency groups](https://docs.github.com/en/actions/using-jobs/using-concurrency).
Not currently using `cancel-in-progress` until [sweepers](https://github.com/honeycombio/terraform-provider-honeycombio/issues/446) are implemented and it's confirmed that they can run when receiving a cancellation signal.

chore: limit integration test concurrency

---

client/v2/client.go
internal/provider/provider.go
internal/provider/query_specification_data_source.go
internal/provider/query_specification_data_source_test.go

Allow 'auto' granularity to be specified as `0`
- Closes #512

fix: allow auto ('0') granularity

---

.github/workflows/ci.yaml
.gitignore
client/v2/api_keys_test.go

In an attempt to make the test output from the client and two provider instances more readable when tests fail, this sets up the [test-summary action](https://github.com/test-summary/action) to parse the any failures generated by the test suite and have them show up on the 'Summary' page of the workflow run ([example](https://github.com/honeycombio/terraform-provider-honeycombio/actions/runs/10180218386)):
Currently showing failed and skipped tests in the summaries.

chore(ci): display test summary output

---

client/v2/limits_test.go

I conflated the logic while hastily adding a test for jitter in #519.
This fixes that flakey test by separating the two paths.

fix(limits): separately test min-max vs header+jitter cases

---

internal/provider/api_key_resource_test.go
internal/provider/honeycombio_sweeper_test.go
internal/provider/provider_test.go
internal/provider/query_resource_test.go
internal/provider/trigger_resource_test.go

We just had a CI failure because of an Environment ([link](https://github.com/honeycombio/terraform-provider-honeycombio/actions/runs/10215780292/attempts/2)) left behind by a previous failed run.
This adds a sweeper for Environments: removing any Environment beginning with `test.`

chore(ci): add environment sweeper

---

client/errors.go
client/errors_test.go
client/v2/client_test.go
go.mod
go.sum

Improves V2 API call error reporting/handling by making use of the JSON:API `source` field ([doc](https://jsonapi.org/format/#error-objects)) in error responses now being sent by the Honeycomb API.
Future work will skip converting these into the RFC7807 'Problem Detail' struct shared with the V1 client and convert them to Terraform diagnostics directly.

chore: improve V2 API error reporting

---

client/burn_alert_test.go
client/v2/client.go
client/v2/limits.go
client/v2/limits_test.go
internal/helper/validation/precision_at_most.go

A new version `golangci-lint` came out and alerted us to some fresh lint errors in the nightly CI run ([link](https://github.com/honeycombio/terraform-provider-honeycombio/actions/runs/10396679826)).
I'm not in love with `min` -> `mini` and `max` -> `maxi` so happy to take naming suggestions #nameingishard

chore: address new linter errors

---

docs/resources/query.md

The example in the documentation for [honeycombio_query](https://registry.terraform.io/providers/honeycombio/honeycombio/latest/docs/resources/query) has the life_cycle block on the wrong resource. Data resources don't accept "replace_triggered_by" blocks.
Updating the documentation on [query resource](https://registry.terraform.io/providers/honeycombio/honeycombio/latest/docs/resources/query)
The lifecycle argument "replace_triggered_by" is defined only for managed resources ("resource" blocks), and is not valid for data resources.
Updating documentation

chore(r/query): improve doc for derived_column

---

internal/models/notification_recipients.go
internal/models/triggers.go
internal/provider/notification_recipients.go
internal/provider/trigger_resource.go
internal/provider/trigger_resource_test.go

`r/trigger` had two nested blocks using structs instead of `types.List` which would cause a Value Conversion error if using a `dynamic` block.
- Closes #537

fix(r/trigger): handle dynamic evaluation schedule

---

docs/data-sources/column.md
docs/data-sources/derived_column.md
docs/data-sources/environment.md
docs/data-sources/environments.md
docs/data-sources/query_result.md
docs/data-sources/recipient.md
docs/data-sources/trigger_recipient.md
docs/resources/api_key.md
docs/resources/column.md
docs/resources/dataset.md
docs/resources/dataset_definitions.md
docs/resources/environment.md
docs/resources/marker.md
docs/resources/marker_setting.md
docs/resources/msteams_recipient.md
docs/resources/query.md
docs/resources/query_annotation.md

Noticed while browsing the provider docs that the use of "callouts" (largely used for notes) is a bit inconsistent.
This change attempts to fix that, while using the available yellow and red [callouts](https://developer.hashicorp.com/terraform/registry/providers/docs#callouts) for warnings and deprecation notices.

chore(docs): standardize use of notes

---

docs/resources/slack_recipient.md
honeycombio/resource_slack_recipient.go

- Closes #533
Updates the Slack channel regex to include channel ids in addition to channels/users beginning with `#` or `@`

feat: slack channel regex accepts channel id

---

client/marker_test.go
client/recipient_test.go
honeycombio/data_source_recipient_test.go
honeycombio/recipients_test.go
internal/helper/test/strings.go

The nightly "smoke test" failed last evening for two reasons:
1) we had an API-side bug when deleting certain shapes of recipients (now fixed)
2) because of the above, there were recipients that were considered duplicates as their Webhook URLs matched (affects Webhook and MSTeams* recipients). In the name of moving toward being able to run these tests concurrently, this fixes that duplicate issue.

fix: generate random URLs for webhook-like recipients

---

honeycombio/resource_column_test.go
honeycombio/resource_derived_column_test.go

With some server-side changes, these two tests have become a bit flakey.
This tidies them up by removing the arguably-unnecessary "destroy check", and ensures that the name used for a bad DC is unique to avoid a false-conflict.
---
- https://app.asana.com/0/0/1208480919302578

fix: column-related test flakes

---

internal/provider/query_specification_data_source.go

While researching an unrelated issue, I came across the documentation on [Local-only Data Sources](https://developer.hashicorp.com/terraform/language/data-sources#local-only-data-sources) and realized the `query_specification` data source should be one and as a result _not_ configure (or require) an API client.

feat(d/query_specification): local-only datasource

---

client/dataset_definitions.go
client/dataset_definitions_test.go
docs/resources/dataset_definitions.md
honeycombio/resource_dataset_definition.go

Adds the two new log-related dataset definitions to `r/dataset_definition`.
---
- https://app.asana.com/0/0/1208492094472237

chore: r/dataset_definition - add log_severity and log_message

---

.github/workflows/ci.yaml

Posts notices to our team alert Slack channel about any failure of a scheduled run (read: not manually triggered or from a PR).
Very open to changing the copy, but this felt 'fine' to me.

chore(ci): notify in Slack if scheduled CI run fails

---

docs/resources/trigger.md

I noticed that the [current docs](https://registry.terraform.io/providers/honeycombio/honeycombio/latest/docs/resources/trigger#example-with-pagerduty-recipient-and-severity) have a malformed second example for Triggers.
This properly tags the code block as HCL which fixes the issue. You can test yourself by copying and pasting the full file into the HashiCorp [Doc Preview Tool](https://registry.terraform.io/tools/doc-preview)

fix(docs): incorrect formatting trigger example

---

.github/workflows/ci.yaml

While "optimal" to have these in place, they end up meaning that the CI workflow doesn't run but it is required for merge -- preventing non-repo-Admins from merging release PRs (mostly notably).
---
- https://app.asana.com/0/0/1208551821723692

chore(ci): remove paths-ignore from CI workflow

---

client/burn_alert.go
internal/provider/burn_alert_resource_test.go

When upgrading to 0.28.0, if you have an existing burn alert that had a description set (via the UI, most likely) but the description was yet to be added to HCL config you will get the following error:
```
Error: Provider produced inconsistent result after apply
When applying changes to honeycombio_burn_alert.test, provider
"provider[\"registry.terraform.io/hashicorp/honeycombio\"]" produced an
unexpected new value: .description: was cty.StringVal(""), but now
cty.StringVal("test description").
```
Fix is to ensure we send the empty string when we marshal our JSON

fix(r/burn_alert): handle existing remote description with default description value

---

.golangci.yml
client/board_test.go
client/burn_alert_test.go
client/column_test.go
client/slo_test.go
honeycombio/data_source_recipient_test.go
honeycombio/data_source_recipients_test.go
honeycombio/data_source_trigger_recipient_test.go
honeycombio/resource_board_test.go
honeycombio/resource_slo.go
honeycombio/resource_slo_test.go
internal/provider/burn_alert_resource_test.go
internal/provider/dataset_resource_test.go
internal/provider/derived_column_data_source_test.go
internal/provider/derived_columns_data_source_test.go
internal/provider/slo_data_source_test.go
internal/provider/slos_data_source_test.go
internal/provider/trigger_resource_test.go
internal/provider/webhook_recipient_resource_test.go

`unparam` felt a bit extra in tests, so disabled it for test files and then cleaned up all the `nolint` directives

chore: tidy up lint config

---

internal/provider/webhook_recipient_resource_test.go

We're seeing a 500 error that I believe is caused by the update in this test not actually updating the template. CI on this branch didn't cause the same 500 so I'd like to merge it in to avoid spamming ourselves with 500s when this test suite runs. I think there's still more to consider about why this is happening both on the TF side and the API side but this is a bandaid for the noise.

fix: webhook recipient test

---

honeycombio/resource_board.go

- Bump up max number of slos on a board from 6 to 24 to match new UI changes

feat(Board, SLO): Bump up max number of SLOs on a board to 24

---

client/recipient.go
client/recipient_test.go
docs/resources/webhook_recipient.md
internal/models/recipients.go
internal/provider/webhook_recipient_resource.go
internal/provider/webhook_recipient_resource_test.go

Support webhook recipient template variables in Terraform

feat: template variables

---

.github/workflows/ci.yaml

Experienced the first timeout during integration tests during last night's scheduled CI run. This simplifies the timeout settings (one for the entire region-scoped job) and increases the limit to 20min.

chore(ci): increase integration test timeout to 20min

---

.github/workflows/ci.yaml
README.md

We inherited codecov when we took this project over from the community, but haven't found it useful and decided to remove it from the project.
As followup once this is landed I'll remove the secret from the project's secrets.

chore(ci): remove codecov

---

internal/provider/trigger_resource.go
internal/provider/trigger_resource_test.go

We received a bug report when using "r/trigger"'s `query_json` attribute handling properly handling equivalent query specifications (e.g. filter order changed, or the default "AND" filter combination was provided).
The error looked something like this:
```
Error: Provider produced inconsistent result after apply
When applying changes to honeycombio_trigger.example, provider
"provider[\"registry.terraform.io/honeycombio/honeycombio\"]" produced an
unexpected new value: .query_json: was
cty.StringVal("{\"calculations\":[{\"op\":\"COUNT\"}],\"filters\":[{\"column\":\"http.status_code\",\"op\":\"\\u003e=\",\"value\":400},{\"column\":\"trace.parent_id\",\"op\":\"does-not-exist\"}],\"filter_combination\":\"AND\",\"time_range\":900}"),
but now …
```

fix(r/trigger): handle state error with equivalent query_json

---

CHANGELOG.md

This preps the CHANGELOG for the v0.28.2 patch release. This is *not* destined for `main`, but instead to `rel-0282` which I forked off the `v0.28.1` tag and cherry-picked cafa068 into it.
Following the successful publishing of v0.28.2 I'll cherry-pick this CHANGELOG commit onto `main`

rel: 0.28.2

---

.github/workflows/ci.yaml
.github/workflows/validate-examples.yml

We've had some CI runs fail with timeouts against the EU region: likely the increased latency just having things take that much longer.
A previous attempt to extend the timeout of the integration test step in the GHA Workflow forgot that the default timeout for `go test` is 10 minutes 🙃. This extends that to 20 for the provider's integration tests and adjusts the GHA `timeout-minutes` values (as the default is 360 minutes)
Fly by fix for the "Validate Examples" job which started failing due to the update to `ubuntu-latest` from what I can tell (which no longer has `terraform` installed by default)

fix(ci): extend 'go test' timeout to 20 min

---

CONTRIBUTING.md
honeycombio/resource_query_annotation.go

https://app.asana.com/0/1202029430213430/1208940043616576
In a [previous, Honeycomb internal PR](https://github.com/honeycombio/hound/pull/21613), we updated the maximum length for query annotation name and description fields.
Now we update those fields in the terraform provider to keep length validation consistent.
Along the way, fix a few typos in `CONTRIBUTING.MD`

fix: update query annotation name and description max length to reflect recent api change

---

go.mod
go.sum

- Closes https://github.com/honeycombio/terraform-provider-honeycombio/security/dependabot/11

build(deps): bump github.com/hashicorp/yamux from 0.1.1 to 0.1.2

---

.golangci.yml

A new version of `golangci-lint` was released which brought improved linters and failed the nightly build ([link](https://github.com/honeycombio/terraform-provider-honeycombio/actions/runs/13319868520)).
All of the linting errors were in the SDKv2 provider which we are slowly moving away from and has been working fine, so I'm choosing to just ignore the lints here.
As a bonus, swapped the deprecated `tenv` linter for it's replacement `usetesting`.

chore: adjust linter config. after golangci-lint update

---

internal/provider/dataset_resource.go

Changing a Dataset's name in place is not supported by the API or the UI.
- Introduced by #535 
---
- https://app.asana.com/0/0/1209390209039954

fix(r/dataset): changing a dataset's name requires replacement

---

docs/resources/slo.md

Derived Columns cannot be removed while in use, which makes renaming a DC used as an SLI a bit of a footgun where you likely run into a `409 Conflict` on apply.
This updates the documented example to follow and recommend this practise.

fix(r/slo): recommend using lifecycle argument to avoid conflicts during derived column updates

---

client/client.go
client/internal/limits/limits.go
client/internal/limits/limits_test.go
client/v2/client.go

With rate limit feedback headers now standard across the V1 and V2 APIs, this tiny refactor has the V1 API client share the retry logic with the V2 API client ✨

feat(client): improve V1 api client retry behaviour

---

.github/workflows/ci.yaml

Skipped tests are about to become more common as we have some features that only work in E&S vs Classic teams.
No need to highlight on the CI summary page.

chore(ci): don't highlight skipped tests

---

internal/provider/webhook_recipient_resource.go

Increase the webhook header char limit to match the updated upstream API limit.

chore(r/webhook_recipient): increase header value char limit

---

docs/resources/burn_alert.md
docs/resources/slo.md
honeycombio/resource_slo.go
honeycombio/resource_slo_test.go
internal/helper/dataset.go
internal/helper/modifiers/dataset_deprecation.go
internal/provider/burn_alert_resource.go
internal/provider/burn_alert_resource_test.go

- Closes https://app.asana.com/0/1205961717360815/1207770326676048/f
- adds multi dataset support for r/burn_alerts by making the `dataset` argument optional.
- add unit tests
- you can check out the **slo_with_burn_alert** example and omit the `dataset` arg.

feat(r/burn_alert): add multi-dataset support

---

go.mod

dependabot incorrectly added a Go 1.24 `toolchain` directive in #650

fix(build): remove incorrect 'toolchain' directive

---

internal/provider/trigger_resource.go
internal/provider/trigger_resource_test.go

Adjust's the validation error message when a Trigger's duration exceeds `4*frequency` to match the UI.
- Closes #653

fix(r/trigger): adjust frequency<>duration validation error message for clarity

---

docs/data-sources/environment.md
internal/models/environments.go
internal/provider/environment_data_source.go
internal/provider/environment_data_source_test.go

Received feedback that looking up environment IDs was a bit awkward.
This allows looking up a single environment via a filter: the "no match" behaviour may feel like a breaking change but when `id` was the only option the data source would fail with 404 anyway, so, the same net-result.

feat(d/environment): add detail_filter to simplify environment lookup

---

client/trigger.go
client/trigger_test.go
docs/resources/trigger.md
example/trigger_with_baseline_details/main.tf
internal/models/triggers.go
internal/provider/trigger_resource.go
internal/provider/trigger_resource_test.go

- https://app.asana.com/1/72322038700732/project/1203970798110426/task/1209772672706729
Adds support for a trigger with a dynamic threshold aka baseline_details. 
pre-reqs:
- run hound in tilt (you need both poodle and public-api)
- in the root, run `make build`
examples:
- in `examples/trigger`, run `terraform init`,`terraform plan` and `terraform apply`
- confirm that the trigger was made in your local poodle ui (with a static threshold)
- in `examples/trigger_with_baseline_details`, run `terraform init`,`terraform plan` and `terraform apply`
- confirm that the trigger was made in your local poodle ui (with a dynamic threshold)
You can adjust the example to test validations: 
- only include one of the `baseline_details` fields, like `type` but no `offset_minutes`
- give it an invalid …

feat(r/trigger): add baseline_details support

---

internal/provider/burn_alert_resource.go
internal/provider/notification_recipients.go
internal/provider/notification_recipients_test.go
internal/provider/trigger_resource.go

We've had multiple reports (and finally a repro. case!) where importing a trigger (or presumably a burn alert) which has one or more recipients with `notification_details` causes an error on `apply` looking something like this:
```
honeycombio_trigger.test: Modifying... [id=2TQRBJ7xp3s]
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to honeycombio_trigger.test, provider "provider[\"registry.terraform.io/honeycombio/honeycombio\"]" produced an unexpected new value: .recipient: planned set element
│ cty.ObjectVal(map[string]cty.Value{"id":cty.StringVal("tqGosJVZzkN"), "notification_details":cty.ListValEmpty(cty.Object(map[string]cty.Type{"pagerduty_severity":cty.String,
│ "variable":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String, …
```

fix(r/trigger,r/burn_alert): gracefully handle recipients with notification details on import

---

README.md

Noticed the CI badge was showing red this morning because some PR workflows were failing: this status badge should be reflective of the health of the `main` branch.
New Markdown was generated by following [these instructions](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/adding-a-workflow-status-badge).

chore(ci): fix CI status badge

---

client/board.go
client/board_test.go
client/trigger.go
client/trigger_test.go
docs/resources/board.md
docs/resources/flexible_board.md
docs/resources/trigger.md
internal/models/flexible_board.go
internal/provider/flexible_board_resource.go
internal/provider/flexible_board_resource_test.go

Adds support for tagging (flexible type) Board resources
update create, read and update methods to support tags on boards.
1. Create a flexible board with tags: 
```
resource "honeycombio_flexible_board" "overview" {
name        = "Now With Tags"
description = "tag all the things"
tags = {
team = "blue"
env = "staging"
}
}
```
2. Update the tags and the state should show the latest updated values

feat(r/flexible_board): add support for tags on Boards

---

client/internal/limits/limits.go
client/internal/limits/limits_test.go

Matching the soon to be released upstream change, this updates `Retry-After` to be parsed properly if we happen to fallback on using it (which, is unlikely to be honest).

fix(client): use proper format for Retry-After fallback

---

docs/index.md
docs/resources/slo.md

The SLO resource has two fields for specifying what dataset the SLO is in: `dataset` and `datasets`.
Our [public API](https://api-docs.honeycomb.io/api/slos/createslo) for SLOs (which the Terraform client uses) expects dataset slugs.
This PR clarifies in our documentation that `dataset` and `datasets` must be dataset slugs, not dataset names.

chore(docs): clarify that dataset and datasets field of slos expect slugs

---

internal/helper/tags.go
internal/provider/slo_resource_test.go
internal/provider/tags.go

Handles setting `tags` to an empty map (e.g. `tags = {}`) without an apply-time error by making the tags default an empty map.
Includes an aliased import cleanup 🧹✨ 
- Closes #699 
---
- https://app.asana.com/0/0/1210526264774553

fix(tags): handle empty tags map

---

internal/helper/modifiers/datasets_require_replace.go
internal/provider/slo_resource.go
internal/provider/slo_resource_test.go

Updating SLO resource after recreation cause the resource to be completely replaced. This was due to `RequiresReplace` forcing a new update everytime.
- add a new plan modifier that only requires the SLO resource to be replaced when `datasets` is changed
- add `UseStateForUnknown` which copies the prior state value, if not null. This will address the bug where the SLO cannot be found during updates
- https://github.com/honeycombio/terraform-provider-honeycombio/issues/701
Updating SLO resource after recreation cause the resource to be completely replaced. This was due to `RequiresReplace` forcing a new update everytime.
- add a new plan modifier that only requires the SLO resource to be replaced when `datasets` is changed
- add `UseStateForUnknown` which copies the prior state value, if …

fix(r/slo): SLO update causing resource replacement

---

docs/resources/flexible_board.md
example/flexible_board/main.tf

A typo i discovered while going through the Honeycomb Terraform provider web pages.
Fixing typo for `board`
N/A

chore(flexible-board): Fix typo in resource description

---

client/trigger.go
client/trigger_test.go

Augment the Honeycomb API client in the `client` package to convey the "dataset_slug" field for triggers. When querying for triggers at the environment level, the API returns all triggers within the environment—including those tied to a particular dataset. Clients can read the populated "dataset_slug" field to distinguish which triggers are tied to which dataset and those that sit at the environment level, above and separate from any particular dataset.
Note that this change does not yet cover [the Terraform provider](https://registry.terraform.io/providers/honeycombio/honeycombio/latest)'s publishing to or querying of data from the Honeycomb API as exposed through its Terraform resources and [data sources](https://registry.terraform.io/providers/honeycombio/honeycombio/latest/docs/resourc …

Accommodate the "dataset_slug" field in triggers

---

client/board.go
client/board_test.go
internal/provider/honeycombio_sweeper_test.go

Adds the missing `dataset` field to the flexible board `QueryPanel` struct.
Originally noted by @seh (with thanks!) the tests in that PR didn't pass, so to avoid the back -- and asking more time of a community member -- I fixed it here.
In the process noticed that some boards weren't getting cleaned up in tests, so added a 'Sweeper' to keep that tidy.
- Replaces #723

fix(client): add missing Dataset field to QueryPanel

---

client/errors.go
docs/index.md
docs/resources/column.md
honeycombio/provider.go
internal/features/README.md
internal/features/defaults.go
internal/features/features.go
internal/features/features_test.go
internal/features/schema.go
internal/provider/column_resource.go
internal/provider/column_resource_test.go
internal/provider/provider.go

This introduces a `features` block to the provider configuration allowing 'feature toggles' to be provided to resources as we see fit. This design is heavily influenced by the Azure Provider.
The first feature toggle is included, enabling the ability for the columns resource to automatically import a column during creation on conflict (which, was the behaviour prior to v0.12.0 of this provider).
The features block is part of the provider configuration and is designed to be extended per resource as we see fit in the future.
To enable the "import on conflict" behavior for the columns resource you would initialize your provider like this:
```hcl
provider "honeycombio" {
features {
column {
import_on_conflict = true
}
}
}
```
This partially resolves #552, and I intend to follow on with an …

feat(features): add features support with column import override

---

docs/resources/query_annotation.md
internal/provider/query_annotation_resource.go
internal/provider/query_annotation_resource_test.go

Fixes the follow error if `description` was empty:
> Error: Provider produced inconsistent result after apply
When applying changes to honeycombio_query_annotation.nice, provider "provider[\"[registry.terraform.io/honeycombio/honeycombio](http://registry.terraform.io/honeycombio/honeycombio)\"]" produced an unexpected new value: .description: was null, but now cty.StringVal("").
This is a bug in the provider, which should be reported in the provider's own issue tracker.
- Introduced by #744

fix(r/query_annotation): handle empty description

---

client/query_spec.go
client/query_spec_test.go
docs/data-sources/query_specification.md
example/query/main.tf
internal/models/query.go
internal/provider/query_specification_data_source.go
internal/provider/query_specification_data_source_test.go

- Terraform support for new field `compare_time_offset_seconds` in the `queries` API 
- API PR is [here](https://github.com/honeycombio/hound/pull/26488)
https://app.asana.com/1/72322038700732/project/1209727892923597/task/1209727895622899?focus=true
Create a quiery using compare_time_offset_seconds, you should get an error when using an invalid option
These are the valid options (all should be in seconds & can be negative or positive values):
- same time as query time range,
- 30 minutes
- 1 hour
- 2 hours
- 8 hours
- 24 hours
- 7 days
- 28 days
- 182 days

feat(queries): Add support for compare_time_offset_seconds
